set(TESTS
    tests/Main.cpp
    tests/RE/A/ActorValues.test.cpp
    tests/RE/B/BSShaderAccumulator.test.cpp
    tests/RE/B/BSInputEventQueue.test.cpp
    tests/RE/F/FormTypes.test.cpp
    tests/RE/I/InventoryChanges.test.cpp
    tests/RE/M/MenuEventHandlerEx.test.cpp
    tests/REL/Relocation.test.cpp
    tests/REL/RuntimeDataAccessors.test.cpp
    tests/REL/StaticAssertSize.test.cpp
    tests/SKSE/Interfaces.test.cpp
    tests/SKSE/Trampoline.test.cpp
)
